### ISSUE TITLE
There was an error retrieving last updated dates

### ISSUE THREAD

**Issue by timur-tabi** [jneilliii/OctoPrint-Python3PluginCompatibilityCheck#1]
Every time I run the plugin, it says this:

> There was an error retrieving last updated dates, either due to rate limiting on Github's API (60 requests per hour) or a plugin's homepage is not configured for a Github repository. Please try again later.

**Comment by timur-tabi** [comment]
This might be related, but your plugin says that "OctoPrint MultiCam" is not compatible, but compatibility was added back in December: https://github.com/mikedmor/OctoPrint_MultiCam/commit/0c1d90ce4fde274b55c1a26bcf37e3cf610dfa2c

**Comment by jneilliii** [comment]
Looks like it's updated in his repository...but not in the Plugin Repository....

![image](https://user-images.githubusercontent.com/5249455/78521250-49ca8e80-7797-11ea-8a4b-ffb25e1a7eaa.png)

May want to open a ticket and let the plugin author know that there is more to do.

If you have OctoLapse installed it will give that notice, as the homepage on the plugin repository does not correspond to FomerLurker's github repository but a website, and that is the URL that is used to check Last Updated date. Not sure how many other plugin's are like that, but it's fairly atypical.

**Comment by timur-tabi** [comment]
I don't have OctoLapse installed.  This is what your plugin reports:

Fullscreen Webcam (12/12/2017)
OctoPrint-Enclosure (03/15/2020)
Octoslack (04/04/2020)
FilamentManager (03/16/2020)
MultiCam (12/05/2019)
The Spaghetti Detective

I'm guessing "The Spaghetti Detective" is the fault because it has no date, and clicking on that link brings me to its non-github repo.

I see what you're saying.  Instead of displaying an ominous error message in red, perhaps you should divide the list into two parts, and the second part is titled something like "Compatibility for the following plugins cannot be determined at this time:".

**Comment by jneilliii** [comment]
I actually already pushed an update that hopefully makes this clearer.
