### ISSUE TITLE
directions on fixing plugins

### ISSUE THREAD

**Issue by aerickson** [jneilliii/OctoPrint-Python3PluginCompatibilityCheck#2]
Thanks for making the plugin. :) I'm a plugin author and my plugins are 'failing' and it was sort of hard to figure out what to do to make this plugin happy.

It seems like authors need to check for Python 3 compatibility and then update their plugin's metadata in https://github.com/OctoPrint/plugins.octoprint.org like:

```
compatibility:
  python: ">=2.7,<4"
```

Is that correct?

--

You may be able to deep link into the 'create an issue' page with something filled out. It would make it easier for end users to report plugin issues (I guess there could be a lot of duplicates if they don't do a search first).

**Comment by aerickson** [comment]
Deeplinking example: https://github.com/isaacs/github/issues/new?title=foo&body=bar

**Comment by jneilliii** [comment]
> Is that correct?

That is correct. You will also have to update your init.py file with the `__plugin_pythoncompat__ = ">=2.7,<4"`

Thanks for the deeplink example, I'll work on getting that updated in the plugin.
